### ISSUE TITLE
POST requests have no output from block

### ISSUE THREAD

**Issue by tyoungNIO** [nio-blocks/http_requests#8]
A successful http POST has no output from the block, where a successful GET does have output. have not tested block output for other http methods.

**Comment by mattdodge** [comment]
The issue happens when a request does not return a JSON parseable response. 

In @tyoungNIO's example, the POST is returning HTML and an warning is being logged. The GET returns valid JSON.

We should enhance the block to still return a signal if the response code matches `2xx` containing the raw response data.

Optionally (up for discussion) include a flag to require that valid JSON gets returned
